/// In the SharedLintState collection: lintSource type-checks scripts through a
/// live FSharpChecker; running that in parallel with AllRulesCoverageTests'
/// project typechecks degrades symbol resolution under coverage instrumentation
/// and FSharpLint then silently drops type-check-gated warnings (e.g. FL0036).
[<Xunit.Collection("SharedLintState")>]
module FSharpLintAnalyzerShim.Tests.IntegrationTests

open Xunit
open Swensen.Unquote
open FSharp.Compiler.CodeAnalysis
open FSharpLint.Application
open FSharp.Analyzers.SDK
open FSharpLintAnalyzerShim.LintAnalyzer

/// One checker for the whole module: a fresh FSharpChecker per test multiplies
/// concurrent FCS state and cold script-options resolution for no test value.
let private checker = FSharpChecker.Create(keepAssemblyContents = true)

let private lintMessages (source: string) : Message list =
    let optionalParams =
        { Lint.OptionalLintParameters.Default with
            Checker = Some checker }

    match Lint.lintSource optionalParams source with
    | Lint.LintResult.Success warnings -> warnings |> List.map mapWarning
    | Lint.LintResult.Failure failure -> failwith $"Lint failed: {failure.Description}"

[<Fact>]
let ``lintSource with interface naming violation produces expected warning`` () =
    let messages =
        lintMessages "module Test\ntype iMyInterface =\n    abstract member DoStuff : unit -> unit\n"

    let interfaceWarnings = messages |> List.filter (fun m -> m.Code = "FL0036")
    test <@ interfaceWarnings.Length > 0 @>
    test <@ interfaceWarnings |> List.exists (fun m -> m.Message.Contains("I")) @>

[<Fact>]
let ``lintSource with clean code produces no warnings`` () =
    let messages = lintMessages "module Test\nlet add x y = x + y\n"
    test <@ messages |> List.isEmpty @>

[<Fact>]
let ``fsharplint:disable-next-line suppresses warning on following line`` () =
    let messages =
        lintMessages
            "module Test\n// fsharplint:disable-next-line\ntype iMyInterface =\n    abstract member DoStuff : unit -> unit\n"

    let interfaceWarnings = messages |> List.filter (fun m -> m.Code = "FL0036")
    test <@ interfaceWarnings |> List.isEmpty @>

[<Fact>]
let ``fsharplint:disable-next-line with specific rule only suppresses that rule`` () =
    let messages =
        lintMessages
            "module Test\n// fsharplint:disable-next-line InterfaceNames\ntype iMyInterface =\n    abstract member DoStuff : unit -> unit\n"

    let interfaceWarnings = messages |> List.filter (fun m -> m.Code = "FL0036")
    test <@ interfaceWarnings |> List.isEmpty @>

[<Fact>]
let ``fsharplint:disable suppresses warnings for rest of file`` () =
    let messages =
        lintMessages
            "module Test\n// fsharplint:disable InterfaceNames\ntype iFirst =\n    abstract member A : unit -> unit\ntype iSecond =\n    abstract member B : unit -> unit\n"

    let interfaceWarnings = messages |> List.filter (fun m -> m.Code = "FL0036")
    test <@ interfaceWarnings |> List.isEmpty @>

[<Fact>]
let ``fsharplint:enable re-enables a previously disabled rule`` () =
    let messages =
        lintMessages
            "module Test\n// fsharplint:disable InterfaceNames\ntype iSuppressed =\n    abstract member A : unit -> unit\n// fsharplint:enable InterfaceNames\ntype iNotSuppressed =\n    abstract member B : unit -> unit\n"

    let interfaceWarnings = messages |> List.filter (fun m -> m.Code = "FL0036")
    test <@ interfaceWarnings.Length > 0 @>
    test <@ interfaceWarnings |> List.forall (fun m -> m.Message.Contains("iNotSuppressed")) @>

/// Regression: xunit.v3.core injects `_content/DefaultRunnerReporters.fs` — a module
/// containing ONLY assembly-level `RegisterRunnerReporter(typeof<…>)` attributes and a
/// bare `do ()` — as a compile item into consuming test projects. With the Xunit types
/// RESOLVED (project context, not a bare script), FSharpLint threw an internal
/// NullReferenceException, which the shim surfaces as FSharpLint.InternalError and CI
/// gates then fail repo-wide (thellma/intelligence AUTOMATION-49). Lint must complete
/// without an internal error on this file shape.
[<Fact>]
let ``module with only assembly attributes and bare do lints without internal error`` () =
    // The exact auto-generated content xunit.v3.core 3.2.x injects (abbreviated to two
    // reporter registrations — the attribute+typeof shape is what matters).
    let xunitDefaultRunnerReportersShape =
        "// <auto-generated> This file has been auto generated by xunit.v3.core. </auto-generated>\n\n"
        + "module internal XunitDefaultRunnerReporters\n\n"
        + "[<assembly: global.Xunit.Runner.Common.RegisterRunnerReporter(typeof<global.Xunit.Runner.Common.AppVeyorReporter>)>]\n"
        + "[<assembly: global.Xunit.Runner.Common.RegisterRunnerReporter(typeof<global.Xunit.Runner.Common.DefaultRunnerReporter>)>]\n"
        + "do ()\n"

    // Resolve the Xunit types for real: reference the xunit assemblies shipped in this
    // test's own bin (the suite runs on xunit.v3) on top of script-derived options.
    let xunitRefs =
        [ "xunit.v3.runner.common.dll"; "xunit.v3.common.dll" ]
        |> List.map (fun d -> System.IO.Path.Combine(System.AppContext.BaseDirectory, d))
        |> List.filter System.IO.File.Exists

    test <@ not (List.isEmpty xunitRefs) @> // harness precondition: refs must exist

    let tempFile =
        System.IO.Path.Combine(System.IO.Path.GetTempPath(), "DefaultRunnerReporters.fs")

    System.IO.File.WriteAllText(tempFile, xunitDefaultRunnerReportersShape)

    let sourceText =
        FSharp.Compiler.Text.SourceText.ofString xunitDefaultRunnerReportersShape

    // The production analyzer host (fshw) runs FCS's TransparentCompiler — its check
    // results differ internally from the background compiler's; match it.
    let checker =
        FSharpChecker.Create(keepAssemblyContents = true, useTransparentCompiler = true)

    let scriptOptions, _ =
        checker.GetProjectOptionsFromScript(tempFile, sourceText, assumeDotNetFramework = false)
        |> Async.RunSynchronously

    let projectOptions =
        { scriptOptions with
            OtherOptions =
                Array.append scriptOptions.OtherOptions (xunitRefs |> List.map (fun r -> $"-r:%s{r}") |> Array.ofList) }

    let parseResults, checkAnswer =
        checker.ParseAndCheckFileInProject(tempFile, 0, sourceText, projectOptions)
        |> Async.RunSynchronously

    let checkResults =
        match checkAnswer with
        | FSharp.Compiler.CodeAnalysis.FSharpCheckFileAnswer.Succeeded r -> r
        | FSharp.Compiler.CodeAnalysis.FSharpCheckFileAnswer.Aborted -> failwith "type check aborted"

    // Harness precondition: the Xunit attribute types must actually resolve — an
    // unresolved-type repro exercises a different code path than production.
    let unresolvedXunit =
        checkResults.Diagnostics |> Array.filter (fun d -> d.Message.Contains "Xunit")

    test <@ Array.isEmpty unresolvedXunit @>

    // Production (the analyzer-host path) supplies project-level check results too —
    // rules and the two-phase ProjectOptions lazy dereference them.
    let projectResults =
        checker.ParseAndCheckProject projectOptions |> Async.RunSynchronously

    let parsedFileInfo: Lint.ParsedFileInformation =
        { Ast = parseResults.ParseTree
          Source = xunitDefaultRunnerReportersShape
          TypeCheckResults = Some checkResults
          ProjectCheckResults = Some projectResults }

    let mutable lintException: exn option = None

    let optionalParams =
        { Lint.OptionalLintParameters.Default with
            ReportLinterProgress =
                Some(fun progress ->
                    match progress with
                    | Lint.ProjectProgress.Failed(_, ex) -> lintException <- Some ex
                    | _ -> ()) }

    match Lint.lintParsedFile optionalParams parsedFileInfo tempFile with
    | Lint.LintResult.Success _ ->
        match lintException with
        | Some ex -> failwith $"FSharpLint internal error:\n{ex}"
        | None -> ()
    | Lint.LintResult.Failure failure -> failwith $"Lint failed: {failure.Description}"
